# Generated by Django 3.0.1 on 2020-01-29 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserPosts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Avatar', models.FileField(default='', upload_to='')),
                ('Name', models.CharField(default='', max_length=128)),
                ('Date', models.DateTimeField(blank=True, null=True)),
                ('Title', models.CharField(default='', max_length=128)),
                ('Media', models.FileField(default='', upload_to='')),
                ('Text', models.TextField(default='')),
                ('Likes', models.BigIntegerField(default=0)),
                ('Dislikes', models.BigIntegerField(default=0)),
                ('PostID', models.CharField(default='', max_length=128)),
            ],
        ),
    ]
